spring.application.name=fleet-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_tracker
spring.datasource.username=postgres
spring.datasource.password=7743

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080


# =========================
# JWT Configuration
# =========================

jwt.secret=4f1b9e29d1b7e17a2e5b0b77c0b2c4a7e3c4f8d5a9b1e2f7d3c6b9a4f1e8d2c5
jwt.expiration=86400000