spring.application.name=fleet-tracker

spring.datasource.url=jdbc:postgresql://ep-holy-star-au3g7t8u-pooler.c-10.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KOI8s9WXnAhy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080


# =========================
# JWT Configuration
# =========================

jwt.secret=4f1b9e29d1b7e17a2e5b0b77c0b2c4a7e3c4f8d5a9b1e2f7d3c6b9a4f1e8d2c5
jwt.expiration=86400000