spring.application.name=fleet-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_tracker
spring.datasource.username=postgres
spring.datasource.password=7743

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080


# ==========================
# JWT Configuration
# ==========================
jwt.secret=9d6c8c9c2b5f4a8e7f1a3b6d9e2f4a7c8b1d3e5f6a8b9c1d2e4f6a8b0c2d4e6
jwt.expiration=86400000